### ISSUE TITLE
Adding "StartCommercial" endpoint

### ISSUE THREAD

**Issue by thormug** [Plazide/node-twitch#13]
Hi,

I just added the startCommercial endpoint on my own.
Don't know anything about typescript so I did it directly on the JS

Just like any other POST endpoint :

/** Start Commercial */
    startCommercial(options) {
        return __awaiter(this, void 0, void 0, function* () {
            if (!this._hasScope("channel:edit:commercial"))
                this._error("Missing scope `channel:edit:commercial`");
			const query = "?" + util_1.parseOptions(options);
            const endpoint = `/channels/commercial${query}`;
            return this._post(endpoint);
        });
    }

**Comment by Plazide** [comment]
Hi,

Thanks for your work, but it really does need to be written in Typescript to be useful. The code you provided doesn't include any types or interfaces for the result of the request. Neither does it provide proper typings for the options to be passed in. These things are done in Typescript.

I'll implement the method as soon as I can.

**Comment by Plazide** [comment]
The `startCommercial` method has been added with version `0.4.0`. If you have any questions or run into problems, feel free to open another issue.
