### ISSUE TITLE
[BUG] Util function isNumber is returning incorrect value

### ISSUE THREAD

**Issue by iXyles** [Plazide/node-twitch#14]
The function in utils called "isNumber" seems to be returning the wrong result.
If the name begins with a number - example "4chan" it will return **true** instead of the expected result **false**. (Noticeable during "getUsers(ids)"). 

What will happen: You will not get the expected user back from twitch, but rather an error saying that the input was wrong, because it added key "id" with user "4chan" instead of "login" & "4chan"

**Comment by Plazide** [comment]
Thanks for reporting this. I thought the tests covered this scenario, but apparently it doesn't.

I'll investigate and fix this after the new year. If you have a solution, feel free to open a PR.

**Comment by Plazide** [comment]
I've published a patch that should fix the issue.

Let me know if the issue persists or not.
