### ISSUE TITLE
Twitch and node Fetch Error

### ISSUE THREAD

**Issue by JDittmerCOM** [Plazide/node-twitch#15]
Hi, for two days now I've only been getting the same error message from my bot.
And all of a sudden, when I have no idea how to solve the problem.

The Pastebin index.js link leads to my complete index.js file which does the whole thing with Twitch. 

**Error message**
```
/opt/discordStreamerBot/node_modules/node-fetch/lib/index.js:272
				return Body.Promise.reject(new FetchError(`invalid json response body at ${_this2.url} reason: ${err.message}`, 'invalid-json'));
				                           ^
FetchError: invalid json response body at https://id.twitch.tv/oauth2/token reason: Unexpected end of JSON input
    at /opt/discordStreamerBot/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (node:internal/process/task_queues:93:5) {
  type: 'invalid-json'
}
```

**Complete index.js file**
[Pastebin: index.js](https://pastebin.com/yxjb3YPQ)

**Comment by Plazide** [comment]
Hey,

That error suggests that there is something wrong with the response from Twitch. It is caused by `node-twitch` trying to parse the response as JSON, but it fails, meaning the response is not valid JSON. I've been trying a few different error cases, and all of them return a JSON response.

I think I'm as lost as you are here, but it might be helpful to know:

 * Does this happen when you use `node-twitch` in other scripts using the same `client_id` and `client_secret`?
 * Does this only happen when calling certain methods, like `getUsers()`, `getStreams`, `getFollows`?
 * Does this happen when you call the same functions outside of your loop?

Hopefully knowing this might give us some idea of what's going on.

**Comment by JDittmerCOM** [comment]
I once did a simple and short test. 

**Test Script**
```javascript
const client = new Discord.Client();
const twitch = new TwitchApi({
	client_id: "xxxxxxxxxxxxxxx",
	client_secret: "xxxxxxxxxxxxxxx"
});


client.once('ready', () => {
	console.log('Ready to rumble!\n');
});

const streams = twitch.getStreams({ channel: "einfachflow" });
console.log(streams);
```

**Result**
```
(node:5331) UnhandledPromiseRejectionWarning: Error: Refresh token is not set.
    at TwitchApi._error (/root/dcbot_test/node_modules/node-twitch/dist/index.js:55:15)
    at TwitchApi.<anonymous> (/root/dcbot_test/node_modules/node-twitch/dist/index.js:92:29)
    at Generator.next (<anonymous>)
    at fulfilled (/root/dcbot_test/node_modules/node-twitch/dist/index.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:5331) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5331) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Plazide** [comment]
That's weird. You should not get that error. This suggests that the call to the Twitch API returned a 401, which shouldn't happen unless you are using methods to call private endpoints, which you are not.

What version of `node-twitch` are you using? (check your package.json)

**Comment by JDittmerCOM** [comment]
```
"discord.js": "^12.3.1",
"node-fetch": "^2.6.1",
**"node-twitch": "^0.4.1",**
```

**Comment by Plazide** [comment]
I can't replicate the issue, so I can't really debug this.

Could you share a repo that reproduces this error?

That might help.

**Comment by JDittmerCOM** [comment]
Here is my test repo
https://github.com/JDittmerCOM/dctest_bot

I removed the Twitch "client_access" and "client_secret", as well as the Discord token in the "config.js" file.
These would have to be inserted yourself.

**Comment by JDittmerCOM** [comment]
So, I tested it again with
```javascript
twitch.getStreams({ channel: "gronkhtv" }).then(test => {
	console.log(test);
});
```
he had no problem with that. However, when it appears to be more data, problems arise again. 
Here is a small part that I do with the console.log. The entire log file is then in the pastebin 

```javascript
function checkStreamers() {
	con.query("SELECT * FROM streamer", async (err1, result1) => {
		if (err1) throw err1;
		result1.forEach(async (streamer) => {
			const streams = await twitch.getStreams({ channel: streamer.name });
			console.log(streams);
```

https://pastebin.com/raw/NSdEsrJy

**Comment by Plazide** [comment]
Thanks,

I've checked it out. While I can't replicate the original error, I managed to get the refresh token error. And it occurs when either the `client_id` or the `client_secret` is incorrect.

I've just pushed an update that adds more detailed error messages when fetching the access token. Could you install that new update (`node-twitch@0.4.2`) and see what errors you get?

**Comment by JDittmerCOM** [comment]
Unfortunately it is still the same error

**Comment by Plazide** [comment]
Exactly the same?

**Comment by JDittmerCOM** [comment]
I updated it via "npm update" and ran the index.js again.  And the log file is just the same, with the same error messages.

**Comment by Plazide** [comment]
Have you checked that the `package.json` says `"node-twitch": "^0.4.2"`?

**Comment by JDittmerCOM** [comment]
This is the current log file 
https://pastebin.com/StNM5Rm0

**Comment by Plazide** [comment]
Ah, I made a mistake when updating. But that's good! Now I know the error occurs where I suspected. I'll push another update in a little while. I'll tell you when I've updated.

**Comment by Plazide** [comment]
Okay, I've updated. Run `npm install node-twitch@0.4.3` to get the latest.

It will not have fixed your error but it should provide more info about what's going on.

**Comment by JDittmerCOM** [comment]
new log file

https://pastebin.com/raw/yj8hsUHc

**Comment by Plazide** [comment]
That's still weird.

The result of calling `https://id.twitch.tv/oauth2/token` is empty. The Twitch documentation doesn't mention anything about an empty response, so I don't know what's causing it or what it means.

I really have no idea what's causing your issue, and since I can't replicate, I can't debug.

I'm just guessing, but it could be something wrong with your application on Twitch. Try creating a new application and use the `client_id` and `client_secret` from that.

**Comment by JDittmerCOM** [comment]
I am already using a new "client_id" and "client_secret" ^^ 
But at least you can now see my problem, that I just have no idea why these messages suddenly appear.

**Comment by JDittmerCOM** [comment]
Maybe I even found the bug. However, I will still have to test the evening.
Will definitely give you feedback if I have tested.

**Comment by JDittmerCOM** [comment]
No, unfortunately it was of no use where I thought it could have solved my problem.
So we are still at the same level as before.

**Comment by Plazide** [comment]
Okay, try this:

Create a `.js` file and paste the following code.

```js
const fetch = require("node-fetch");

async function init(){
	const data = {
		client_id: "xxxxxxxxxxxxx",
		client_secret: "xxxxxxxxxxxxxxxx",
		grant_type: "client_credentials"
	};

	const endpoint = "https://id.twitch.tv/oauth2/token"
	const response = await fetch(endpoint, {
		method: "POST",
		body: JSON.stringify(data),
		headers: {
			"Content-Type": "application/json"
		}
	})

	const result = await response.json();
	console.log(result)
}

init();
```

When you run it, it should log something like this:

```js
{
  access_token: 'xxxxxxxxxxxxxxx',
  expires_in: 5342568,
  token_type: 'bearer'
}
```

This is what `node-twitch` does to get the app access token. If you get an empty response, ie. invalid JSON, here too, then it means the error is completely on Twitch's side. If you instead get a valid JSON response, the error is most likely somewhere in `node-twitch`. 

Let me know how it goes.

**Comment by JDittmerCOM** [comment]
So at least I got a successful result. 

```
{
  access_token: '0usn8gjz4xcv6mbxxxxxxxxxxxxxxxx',
  expires_in: 5019211,
  token_type: 'bearer'
}
```

**Comment by JDittmerCOM** [comment]
I have the feeling that it causes problems as soon as it is in the SQL execution and iterates through all the records. 
There are currently 234 entries.

**Comment by Plazide** [comment]
Hmm...

If you are making that many requests, it could be a rate limit issue. You could try to use the `channels` option instead, and pass an array of login names/user ids. This would get all of the streams in a single request, which would avoid the rate limit. But you'd have to keep in mind that you can only pass in up to 100 channels, so you would have to batch them into arrays of 100 each.

so you would do something like this:

```js
const streamers = ["streamer1", "streamer2", "streamer3"]
const streams = await twitch.getStreams({ channels: streamers });
console.log(streams);
```

**Comment by JDittmerCOM** [comment]
After a few hours of trying and testing, testing, testing, it now seems to be working.
I have a maximum of 50 entries per array.

I have now got results back WITHOUT error messages.

Does this only list the people who are currently live on Twitch?

**Comment by Plazide** [comment]
Great!

It seems like it was a rate limit issue then.

Yes, only streams that are live will be included in the results.

**Comment by JDittmerCOM** [comment]
As soon as I have finished rewriting the bot and everything should really work out in the end, I will give you one final notice and then close the issue.

In any case, big thanks for the whole thing :)

**Comment by JDittmerCOM** [comment]
Hi, sorry for the late response.

I have rewritten my bot for Discord so far and it works again with your npm function.
I still have to adjust a little something with which I still have problems, but generally it works again :)

Thanks again for troubleshooting and everything else 👍🏻
