### ISSUE TITLE
dist/util.js cannot find "fs" library

### ISSUE THREAD

**Issue by K5qu4r3d** [Plazide/node-twitch#20]
Hi.

I have installed the package using `npm`, and set up the code as shown under "Usage" on the README. However, I encounter this error when running my app:

```
error - ./node_modules/node-twitch/dist/util.js:7:0
Module not found: Can't resolve 'fs'
```

Here is my `package.json`:

```
{
  "name": "with-typescript-styled-components",
  "version": "1.0.0",
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@types/axios": "^0.14.0",
    "@types/lodash.includes": "^4.3.6",
    "@types/lodash.remove": "^4.7.6",
    "@types/tmi.js": "^1.7.1",
    "@types/url-parse": "^1.4.3",
    "axios": "^0.21.1",
    "lodash.find": "^4.6.0",
    "lodash.includes": "^4.3.0",
    "lodash.remove": "^4.7.0",
    "next": "latest",
    "node-twitch": "^0.4.3",
    "react": "^16.13.0",
    "react-dom": "^16.13.0",
    "styled-components": "^5.0.0",
    "tmi.js": "^1.7.5",
    "url-parse": "^1.5.1"
  },
  "devDependencies": {
    "@types/lodash.find": "^4.6.6",
    "@types/node": "12.0.12",
    "@types/react": "16.8.23",
    "@types/react-dom": "16.8.4",
    "@types/styled-components": "5.0.1",
    "babel-plugin-styled-components": "^1.10.0",
    "typescript": "4.0"
  },
  "license": "MIT"
}
```

Is there something I am missing during installation?

**Comment by Plazide** [comment]
Hey, sorry for the late response.

Have you managed to solve it? If not, could you provide a repo for reproduction?

**Comment by K5qu4r3d** [comment]
Hi, sorry for the late response. Thank you for reaching out to help.

I solved this issue. I figured out that since I'm using `next.js` I need to use its data-fetching functions e.g. `getStaticProps`. This is because `next.js` keeps most of its code exclusively in the server, so by using those functions I ensure that `node-twitch` doesn't get accessed by the client.

**Comment by Plazide** [comment]
Okay, glad you figured it out!
