### ISSUE TITLE
Wrong interpretation of users login / ids

### ISSUE THREAD

**Issue by alacroix** [Plazide/node-twitch#22]
Hi 👋 

I found an issue when using the `getUsers` method with "weird" usernames (mine in this case).

My login name on Twitch is `0xbabe`.

If we use directly the Helix API, it works:

https://api.twitch.tv/helix/users?login=0xbabe
```
{"data":[{"id":"196242576","login":"0xbabe","display_name":"0xBABE","type":"","broadcaster_type":"","description":"","profile_image_url":"https://static-cdn.jtvnw.net/user-default-pictures-uv/ead5c8b2-a4c9-4724-b1dd-9f00b46cbd3d-profile_image-300x300.png","offline_image_url":"","view_count":652,"created_at":"2018-02-13T19:20:38.754337Z"}]}
```

However, with this wrapper, I've got the following error:
```
{
  error: 'Bad Request',
  status: 400,
  message: 'Invalid login names, emails or IDs in request'
}
```

I deep dived quickly into the source code and found this:

```typescript
async getUsers(
	ids: string | number | string[] | number[]
): Promise<APIUserResponse>{
	let query = "?";

	if(Array.isArray(ids)){
		query += parseMixedParam({ values: ids, stringKey: "login", numericKey: "id" });
	}else{
		const key = isNumber("" + ids) ? "id" : "login";
		query += `${key}=${ids}`;
	}

	const endpoint = "/users" + query;
	return this._get<APIUserResponse>(endpoint);
}
```

It uses `isNumber`, a custom helper: 

```typescript
export function isNumber(value: unknown): boolean{
	if(typeof value === "undefined") return false;
	if(value === null) return false;

	return !isNaN(Number("" + value));
}
```

The problem here is that `Number("0xbabe")` returns a valid number (cuz it's a valid hex string), and then it's interpreted as an id and not as a login.

Do you have an idea how to solve this? I've scratched my head a bit but didn't found clean ways how to do this.

Thanks!

**Comment by Plazide** [comment]
Thanks for reporting this.

I didn't consider that users might use hex values as login names (probably should have). I think this should be handled as an edge case by simply checking if the provided value contains `0x` or simply `x`. If the provided value contains an `x`, we can be certain that the value is not a number and just return false.

It can be done using the following code:
```js
function isNumber(value: unknown){
  ...
  if(("" + value).includes("x")) return false;
  ...
}
```

Let me know if you want to make a PR. Otherwise, I'll fix this later this week.

**Comment by alacroix** [comment]
Great, thanks!

Will do the PR later today 😃

**Comment by alacroix** [comment]
PR ready @Plazide 👍

**Comment by Plazide** [comment]
Hey @alacroix 

A new version of the package has been published to NPM. Install `node-twitch@0.4.4` to get the new code!

Thanks for reporting and fixing!

**Comment by alacroix** [comment]
Great! Thank you for your fast answer and release :)

**Comment by Plazide** [comment]
No problem!
