### ISSUE TITLE
Missed typings

### ISSUE THREAD

**Issue by LWJerri** [Plazide/node-twitch#26]
Hello! `Stream` type missed this types:
- user_login
- game_name
- is_mature

**Comment by Plazide** [comment]
Thanks for reporting. Will update ASAP.

**Comment by Dep0sit** [comment]
And this one too

**Comment by B4TT3RY** [comment]
Any updates?
![image](https://user-images.githubusercontent.com/12368101/154838465-893ce96d-f731-49bf-be1a-0e1fed323e39.png)
I can't find `game_name` in `Stream`.

**Comment by coffee-converter** [comment]
@Plazide looks like these are added in master but not included in any new release...do you have one planned soon?
