### ISSUE TITLE
fetch error when trying to implement with vuejs

### ISSUE THREAD

**Issue by 3V1LXD** [Plazide/node-twitch#28]
Uncaught (in promise) TypeError: 'fetch' called on an object that does not implement interface Window.

main.js
```
import TwitchApi from "node-twitch";
const twitch = new TwitchApi({
  client_id: "xxx",
  client_secret: "xxx"
});
Vue.prototype.$twitch = twitch;
```

Home.vue
```
async getStreams(pagination) {
 let streams;
 if (pagination) {
         streams = await this.$twitch.getStreams({ first: 30, after: pagination });
  } else {
         streams = await this.$twitch.getStreams({ first: 30 });
  }
 console.log(streams);
 this.pagination = streams.pagination;
}
```

**Comment by Plazide** [comment]
Hey,

This package is meant to be used in a NodeJS server environment. The browser, therefore Vue, is not a supported runtime. You should also not expose your `client_secret` in your frontend code.

I would suggest adding a server to your project, or a serverless function, to make calls with `node-twitch`. 

Hope that helps.

**Comment by 3V1LXD** [comment]
I see. I figured that was the issue but I'm very bad at interpreting errors. Currently my project is for learning purposes. Thanks.
