### ISSUE TITLE
Event Listeners

### ISSUE THREAD

**Issue by magicmonkey88** [Plazide/node-twitch#41]
Are there any Event listeners on here by chance?

**Comment by Plazide** [comment]
Hey,

There are currently only two event emitters. One fires when a new refresh token has been fetched and is called `refresh`. The other one fires when user authentication has been preformed and is called `user_auth`.

We do not have event emitters that are connected to pub/sub or webhooks.

You should be able to listen to events by using `twitch.on("refresh", () => { // Do things })` on an instantiated twitch object.

I hope that answers your question.
