### ISSUE TITLE
Validating Tokens

### ISSUE THREAD

**Issue by lugonpedro** [Plazide/node-twitch#52]
_(First of all sorry for my english, I'm learning)_

Twitch API has token validation in his docs (https://dev.twitch.tv/docs/authentication/validate-tokens/), all I want to know is there is a method to validate this in node-twitch, it is not necessary or I do this on my own?

Thanks for your time!

**Comment by Plazide** [comment]
Well, there is a method for validation oauth tokens, but it is not intended to be used by users of the package. It is an internal method. We call it when we need to [refresh the access token](https://github.com/Plazide/node-twitch/blob/master/src/index.ts#L157).

You should be able to access it if you need to, but keep in mind that it might change behavior unexpectedly. You can look at the [_validate() method](https://github.com/Plazide/node-twitch/blob/master/src/index.ts#L206) to see how it works.

So, my answer is that **you do not need to validate the token on your own, we handle this automatically**.

**Comment by lugonpedro** [comment]
Thank you one more time!
